import Document, { DocumentContext, Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    const initialProps = await Document.getInitialProps(ctx)
    return initialProps
}

  render() {
    return (
      <Html>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <meta name="robots" content="noindex"/>
          <link rel="apple-touch-icon" type="image/png" href="/apple-touch-icon-180x180.png"/>
          <link rel="icon" type="image/png" href="/icon-192x192.png"/>
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com"/>
          <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet"/>
        </Head>
        <body className="custom_class">
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument